name: "Terraform"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  foo-dev:
    name: "Foo DEV"
    runs-on: ubuntu-latest
    environment: dev
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Plan
        id: plan
        #working-directory: ./environments/dev
        uses: ./.github/actions/terraform-plan
        with:
          deployment-environment: dev

      - name: Apply
        id: apply
        #working-directory: ./environments/dev
        uses: ./.github/actions/terraform-apply
        with:
          deployment-environment: dev

  foo-int:
    name: "Foo INT"
    runs-on: ubuntu-latest
    environment: int
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Plan
        id: plan
        #working-directory: ./environments/int
        uses: ./.github/actions/terraform-plan
        with:
          deployment-environment: int

      - name: Apply
        id: apply
        #working-directory: ./environments/int
        uses: ./.github/actions/terraform-apply
        with:
          deployment-environment: int

