name: "Terraform"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions: write-all

jobs:

  foo-dev:
    name: "Foo DEV"
    runs-on: ubuntu-latest
    environment: dev
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Plan
        id: plan
        uses: ./.github/actions/terraform-plan
        with:
          deployment-environment: dev
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Apply
        id: apply
        uses: ./.github/actions/terraform-apply
        with:
          deployment-environment: dev

  foo-int:
    name: "Foo INT"
    runs-on: ubuntu-latest
    environment: int
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Plan
        id: plan
        uses: ./.github/actions/terraform-plan
        with:
          deployment-environment: int
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Apply
        id: apply
        uses: ./.github/actions/terraform-apply
        with:
          deployment-environment: int

