name: "Terraform"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Plan Dev
        environment: dev
        id: plan-dev
        working-directory: ./environments/dev
        uses: ./.github/actions/terraform-plan
        with:
          deployment-environment: dev

      - name: Apply Dev
        environment: dev
        id: apply-dev
        working-directory: ./environments/dev
        uses: ./.github/actions/terraform-apply
        with:
          deployment-environment: dev

      - name: Plan Int
        environment: int
        id: plan-int
        working-directory: ./environments/int
        uses: ./.github/actions/terraform-plan
        with:
          deployment-environment: int

      - name: Apply Int
        environment: int
        id: apply-int
        working-directory: ./environments/int
        uses: ./.github/actions/terraform-apply
        with:
          deployment-environment: int
